name: book_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.0
  dropdown_search: ^5.0.6
  expandable: ^5.0.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  form_field_validator: ^1.1.0
  intl_phone_field: ^3.1.0
  mask_text_input_formatter: ^2.4.0
  otp_text_field: ^1.1.3
  phone_number: ^1.0.0
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.1
  image_picker: ^0.8.8
  firebase_storage: ^11.2.2
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  # - image/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
